import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { PlayerTracksProvider } from "@/context/PlayerTracksContext";
import AudioPlayer from "@/components/domain/AudioPlayer";
import { Suspense } from "react";
import Loading from "@/components/ui/loading";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "SoundCloud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <PlayerTracksProvider>
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <AudioPlayer />
        </PlayerTracksProvider>
      </body>
    </html>
  );
}
